apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp-deploy
  template:
    metadata:
      labels:
        app: ftp-deploy
    spec:
      containers:
      - name: app
        image: alvarodoca/ftp-deploy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: aws-secrets